# -*- mode: python -*-

import os

env = Environment(ENV = {'PATH' : os.environ['PATH']}, tools=['default', 'ascons'])
env.requireVersion('1.0.3')

env.SConscript(dirs='.',
               exports='env',
               variant_dir=env['BUILD_DIR'],
               duplicate=1
               )
